global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: 'https://webhook.site/9db0206c-3d3c-47c9-b33b-b7b0291c7541'
        send_resolved: false




# alertmanager --config.file=alertmanager.yml