global:
  scrape_interval: 15s
  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost: 9093

scrape_configs:
  # scrape for go application
  - job_name: "goApplication"
    static_configs:
      - targets: ["localhost:8080"]

  # for node exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
