global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/7fe1ae15-1959-4af3-bc90-d699c7f1c152'
          send_resolved: false